# Generated by Django 5.1.9 on 2026-02-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_location',
        ),
    ]
