# Generated by Django 6.0.2 on 2026-02-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_otp_email_otp_pending_data_alter_otp_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_image',
            field=models.ImageField(blank=True, help_text='Aadhaar card image (uploaded to Cloudinary)', null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for KYC rejection', null=True),
        ),
    ]
