# Generated by Django 6.0.2 on 2026-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user_aadhar_image_user_aadhar_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar_image',
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_back_image',
            field=models.ImageField(blank=True, help_text='Aadhaar card back image (uploaded to Cloudinary)', null=True, upload_to='kyc/aadhar/back/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_front_image',
            field=models.ImageField(blank=True, help_text='Aadhaar card front image (uploaded to Cloudinary)', null=True, upload_to='kyc/aadhar/front/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
    ]
