# Generated by Django 6.0.2 on 2026-02-09 08:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_user_aadhar_image_user_aadhar_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_back_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Aadhaar card back image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_front_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Aadhaar card front image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
