# Generated by Django 6.0.2 on 2026-02-16 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_user_aadhar_back_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFABackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='8-character backup code', max_length=12, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Backup Code',
                'verbose_name_plural': 'MFA Backup Codes',
                'db_table': 'mfa_backup_codes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFASession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, help_text='Temporary token for MFA verification', max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Session',
                'verbose_name_plural': 'MFA Sessions',
                'db_table': 'mfa_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFAVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('method_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Verification Code',
                'verbose_name_plural': 'MFA Verification Codes',
                'db_table': 'mfa_verification_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFALoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure (invalid code, expired, etc)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mfa_login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Login Attempt',
                'verbose_name_plural': 'MFA Login Attempts',
                'db_table': 'mfa_login_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'ip_address', 'created_at'], name='mfa_login_a_email_fea9ce_idx'), models.Index(fields=['ip_address', 'created_at'], name='mfa_login_a_ip_addr_e7ca99_idx')],
            },
        ),
        migrations.CreateModel(
            name='MFAMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('totp', 'TOTP (Authenticator App)'), ('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('secret_key', models.CharField(blank=True, help_text='Base32 encoded secret for TOTP', max_length=32, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for SMS MFA', max_length=17, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary MFA method')),
                ('is_enabled', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Method',
                'verbose_name_plural': 'MFA Methods',
                'db_table': 'mfa_methods',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('user', 'method_type')},
            },
        ),
    ]
