# Generated by Django 6.0.2 on 2026-02-17 04:37

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_mfabackupcode_mfasession_mfaverificationcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mfabackupcode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mfaloginattempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mfamethod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mfasession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mfaverificationcode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_role_0ace22_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_emai_476443_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_kyc_sta_4052e1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mfamethod',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mfabackupcode',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='mfaloginattempt',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mfamethod',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mfamethod',
            name='method_type',
            field=models.CharField(choices=[('totp', 'Authenticator App'), ('email', 'Email')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mfamethod',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mfasession',
            name='session_token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='mfaverificationcode',
            name='method_type',
            field=models.CharField(choices=[('email', 'Email')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_back_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_front_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Invalid phone format')]),
        ),
        migrations.AlterModelTable(
            name='mfabackupcode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mfamethod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mfasession',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mfaverificationcode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='otp',
            table=None,
        ),
        migrations.RemoveField(
            model_name='mfamethod',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='mfamethod',
            name='updated_at',
        ),
    ]
