# Generated by Django 6.0.2 on 2026-02-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_mfabackupcode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
