# Generated by Django 5.1.9 on 2026-03-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancellation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
